[package]
name = "ilang"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler = { path = "../compiler" }
libloading = "0.8.6"

[dependencies.pyo3]
version = "0.27.2"
features = ["extension-module"]
